export const styleEntries = {
  badge: ['src/components/Badge/badge.css'],
  'bottom-app-bar': ['src/components/BottomAppBar/bottom-app-bar.css'],
  'bottom-sheet': ['src/components/BottomSheet/bottom-sheet.css'],
  'bottom-sheet-scaffold': [
    'src/components/Scaffold/scaffold.css',
    'src/components/BottomSheet/bottom-sheet.css',
    'src/components/BottomSheetScaffold/bottom-sheet-scaffold.css',
  ],
  button: [
    'src/internal/ripple/ripple.css',
    'src/components/Button/button.css',
  ],
  'button-group': [
    'src/internal/ripple/ripple.css',
    'src/components/Button/button.css',
    'src/components/IconButton/icon-button.css',
    'src/components/ButtonGroup/button-group.css',
  ],
  card: [
    'src/internal/ripple/ripple.css',
    'src/internal/elevation/elevation.css',
    'src/components/Card/card.css',
  ],
  carousel: ['src/components/Carousel/carousel.css'],
  checkbox: [
    'src/internal/ripple/ripple.css',
    'src/components/Checkbox/checkbox.css',
  ],
  chip: [
    'src/internal/ripple/ripple.css',
    'src/internal/elevation/elevation.css',
    'src/components/Chip/chip.css',
  ],
  'date-picker': [
    'src/internal/ripple/ripple.css',
    'src/components/IconButton/icon-button.css',
    'src/components/DatePicker/date-picker.css',
  ],
  dialog: [
    'src/internal/ripple/ripple.css',
    'src/components/Button/button.css',
    'src/components/Dialog/dialog.css',
  ],
  divider: ['src/components/Divider/divider.css'],
  'drag-handle': [
    'src/internal/ripple/ripple.css',
    'src/components/DragHandle/drag-handle.css',
  ],
  fab: [
    'src/internal/ripple/ripple.css',
    'src/internal/elevation/elevation.css',
    'src/components/Fab/fab.css',
  ],
  'fab-menu': [
    'src/internal/ripple/ripple.css',
    'src/internal/elevation/elevation.css',
    'src/components/Surface/surface.css',
    'src/components/Fab/fab.css',
    'src/components/FabMenu/fab-menu.css',
  ],
  'floating-toolbar': ['src/components/FloatingToolbar/floating-toolbar.css'],
  'icon-button': [
    'src/internal/ripple/ripple.css',
    'src/components/IconButton/icon-button.css',
  ],
  'list-item': [
    'src/internal/ripple/ripple.css',
    'src/internal/elevation/elevation.css',
    'src/components/ListItem/list-item.css',
  ],
  'loading-indicator': ['src/components/LoadingIndicator/loading-indicator.css'],
  'navigation-bar': [
    'src/internal/ripple/ripple.css',
    'src/components/NavigationBar/navigation-bar.css',
  ],
  'navigation-drawer': [
    'src/internal/ripple/ripple.css',
    'src/components/NavigationDrawer/navigation-drawer.css',
  ],
  'navigation-rail': [
    'src/internal/ripple/ripple.css',
    'src/components/NavigationRail/navigation-rail.css',
  ],
  'wide-navigation-rail': [
    'src/internal/ripple/ripple.css',
    'src/components/WideNavigationRail/wide-navigation-rail.css',
  ],
  'modal-wide-navigation-rail': [
    'src/internal/ripple/ripple.css',
    'src/components/Scrim/scrim.css',
    'src/components/WideNavigationRail/wide-navigation-rail.css',
    'src/components/WideNavigationRail/modal-wide-navigation-rail.css',
  ],
  'progress-indicator': ['src/components/ProgressIndicator/progress-indicator.css'],
  'pull-to-refresh': [
    'src/components/ProgressIndicator/progress-indicator.css',
    'src/components/PullToRefresh/pull-to-refresh.css',
  ],
  'radio-button': [
    'src/internal/ripple/ripple.css',
    'src/components/RadioButton/radio-button.css',
  ],
  scaffold: ['src/components/Scaffold/scaffold.css'],
  scrim: ['src/components/Scrim/scrim.css'],
  'search-bar': [
    'src/internal/elevation/elevation.css',
    'src/components/SearchBar/search-bar.css',
  ],
  'segmented-button': [
    'src/internal/ripple/ripple.css',
    'src/components/SegmentedButton/segmented-button.css',
  ],
  slider: [
    'src/internal/ripple/ripple.css',
    'src/components/Slider/slider.css',
  ],
  'split-button': [
    'src/internal/ripple/ripple.css',
    'src/components/Button/button.css',
    'src/components/SplitButton/split-button.css',
  ],
  snackbar: [
    'src/internal/ripple/ripple.css',
    'src/components/Button/button.css',
    'src/components/IconButton/icon-button.css',
    'src/components/Snackbar/snackbar.css',
  ],
  switch: [
    'src/internal/ripple/ripple.css',
    'src/components/Switch/switch.css',
  ],
  tabs: [
    'src/internal/ripple/ripple.css',
    'src/components/Divider/divider.css',
    'src/components/Tabs/tabs.css',
  ],
  'text-field': ['src/components/TextField/text-field.css'],
  'time-picker': [
    'src/internal/ripple/ripple.css',
    'src/components/Button/button.css',
    'src/components/TimePicker/time-picker.css',
  ],
  'toggle-button': [
    'src/internal/ripple/ripple.css',
    'src/components/Button/button.css',
    'src/components/ToggleButton/toggle-button.css',
  ],
  'top-app-bar': ['src/components/TopAppBar/top-app-bar.css'],
  tooltip: ['src/components/Tooltip/tooltip.css'],
};

export const publicComponentStyleSources = {
  badge: 'src/components/Badge/badge.css',
  'bottom-app-bar': 'src/components/BottomAppBar/bottom-app-bar.css',
  'bottom-sheet': 'src/components/BottomSheet/bottom-sheet.css',
  'bottom-sheet-scaffold':
    'src/components/BottomSheetScaffold/bottom-sheet-scaffold.css',
  button: 'src/components/Button/button.css',
  'button-group': 'src/components/ButtonGroup/button-group.css',
  card: 'src/components/Card/card.css',
  carousel: 'src/components/Carousel/carousel.css',
  checkbox: 'src/components/Checkbox/checkbox.css',
  chip: 'src/components/Chip/chip.css',
  'date-picker': 'src/components/DatePicker/date-picker.css',
  dialog: 'src/components/Dialog/dialog.css',
  divider: 'src/components/Divider/divider.css',
  'drag-handle': 'src/components/DragHandle/drag-handle.css',
  fab: 'src/components/Fab/fab.css',
  'fab-menu': 'src/components/FabMenu/fab-menu.css',
  'floating-toolbar': 'src/components/FloatingToolbar/floating-toolbar.css',
  'icon-button': 'src/components/IconButton/icon-button.css',
  'list-item': 'src/components/ListItem/list-item.css',
  'loading-indicator': 'src/components/LoadingIndicator/loading-indicator.css',
  'navigation-bar': 'src/components/NavigationBar/navigation-bar.css',
  'navigation-drawer': 'src/components/NavigationDrawer/navigation-drawer.css',
  'navigation-rail': 'src/components/NavigationRail/navigation-rail.css',
  'wide-navigation-rail': 'src/components/WideNavigationRail/wide-navigation-rail.css',
  'modal-wide-navigation-rail':
    'src/components/WideNavigationRail/modal-wide-navigation-rail.css',
  'progress-indicator': 'src/components/ProgressIndicator/progress-indicator.css',
  'pull-to-refresh': 'src/components/PullToRefresh/pull-to-refresh.css',
  'radio-button': 'src/components/RadioButton/radio-button.css',
  scaffold: 'src/components/Scaffold/scaffold.css',
  scrim: 'src/components/Scrim/scrim.css',
  'search-bar': 'src/components/SearchBar/search-bar.css',
  'segmented-button': 'src/components/SegmentedButton/segmented-button.css',
  slider: 'src/components/Slider/slider.css',
  'split-button': 'src/components/SplitButton/split-button.css',
  snackbar: 'src/components/Snackbar/snackbar.css',
  switch: 'src/components/Switch/switch.css',
  tabs: 'src/components/Tabs/tabs.css',
  'text-field': 'src/components/TextField/text-field.css',
  'time-picker': 'src/components/TimePicker/time-picker.css',
  'toggle-button': 'src/components/ToggleButton/toggle-button.css',
  'top-app-bar': 'src/components/TopAppBar/top-app-bar.css',
  tooltip: 'src/components/Tooltip/tooltip.css',
};

export const publicComponentModules = {
  badge: 'src/components/Badge/Badge.tsx',
  'bottom-app-bar': 'src/components/BottomAppBar/BottomAppBar.tsx',
  'bottom-sheet': 'src/components/BottomSheet/BottomSheet.tsx',
  'bottom-sheet-scaffold':
    'src/components/BottomSheetScaffold/BottomSheetScaffold.tsx',
  button: 'src/components/Button/Button.tsx',
  'button-group': 'src/components/ButtonGroup/ButtonGroup.tsx',
  card: 'src/components/Card/Card.tsx',
  carousel: 'src/components/Carousel/Carousel.tsx',
  checkbox: 'src/components/Checkbox/Checkbox.tsx',
  chip: 'src/components/Chip/Chip.tsx',
  'date-picker': 'src/components/DatePicker/DatePicker.tsx',
  dialog: 'src/components/Dialog/Dialog.tsx',
  divider: 'src/components/Divider/Divider.tsx',
  'drag-handle': 'src/components/DragHandle/DragHandle.tsx',
  fab: 'src/components/Fab/Fab.tsx',
  'fab-menu': 'src/components/FabMenu/FabMenu.tsx',
  'floating-toolbar': 'src/components/FloatingToolbar/FloatingToolbar.tsx',
  'icon-button': 'src/components/IconButton/IconButton.tsx',
  'list-item': 'src/components/ListItem/ListItem.tsx',
  'loading-indicator': 'src/components/LoadingIndicator/LoadingIndicator.tsx',
  'navigation-bar': 'src/components/NavigationBar/NavigationBar.tsx',
  'navigation-drawer': 'src/components/NavigationDrawer/NavigationDrawer.tsx',
  'navigation-rail': 'src/components/NavigationRail/NavigationRail.tsx',
  'wide-navigation-rail': 'src/components/WideNavigationRail/WideNavigationRail.tsx',
  'modal-wide-navigation-rail':
    'src/components/WideNavigationRail/ModalWideNavigationRail.tsx',
  'progress-indicator': 'src/components/ProgressIndicator/ProgressIndicator.tsx',
  'pull-to-refresh': 'src/components/PullToRefresh/PullToRefresh.tsx',
  'radio-button': 'src/components/RadioButton/RadioButton.tsx',
  scaffold: 'src/components/Scaffold/Scaffold.tsx',
  scrim: 'src/components/Scrim/Scrim.tsx',
  'search-bar': 'src/components/SearchBar/SearchBar.tsx',
  'segmented-button': 'src/components/SegmentedButton/SegmentedButton.tsx',
  slider: 'src/components/Slider/Slider.tsx',
  'split-button': 'src/components/SplitButton/SplitButton.tsx',
  snackbar: 'src/components/Snackbar/Snackbar.tsx',
  switch: 'src/components/Switch/Switch.tsx',
  tabs: 'src/components/Tabs/Tabs.tsx',
  'text-field': 'src/components/TextField/TextField.tsx',
  'time-picker': 'src/components/TimePicker/TimePicker.tsx',
  'toggle-button': 'src/components/ToggleButton/ToggleButton.tsx',
  'top-app-bar': 'src/components/TopAppBar/TopAppBar.tsx',
  tooltip: 'src/components/Tooltip/Tooltip.tsx',
};
