import type { MDXComponents } from 'mdx/types';
import type { ComponentType } from 'react';
import { MdxClientComponent } from './mdx-client';

type ClientMdxProps = Record<string, unknown>;

function clientComponent(name: string): ComponentType<ClientMdxProps> {
  function ClientMdxProxy(props: ClientMdxProps) {
    return <MdxClientComponent name={name} {...props} />;
  }

  ClientMdxProxy.displayName = `DocsMdx(${name})`;
  return ClientMdxProxy;
}

export const docsMdxComponents = {
  h1: clientComponent('h1'),
  h2: clientComponent('h2'),
  h3: clientComponent('h3'),
  h4: clientComponent('h4'),
  p: clientComponent('p'),
  li: clientComponent('li'),
  a: clientComponent('a'),
  code: clientComponent('code'),
  pre: clientComponent('pre'),
  blockquote: clientComponent('blockquote'),
  table: clientComponent('table'),
  th: clientComponent('th'),
  td: clientComponent('td'),
  ComponentPreview: clientComponent('ComponentPreview'),
  LiveExample: clientComponent('LiveExample'),
  MaterialParity: clientComponent('MaterialParity'),
  ParitySummary: clientComponent('ParitySummary'),
  ApiReference: clientComponent('ApiReference'),
  MaterialSpecTable: clientComponent('MaterialSpecTable'),
  ColorRoleGrid: clientComponent('ColorRoleGrid'),
  DynamicColorPreview: clientComponent('DynamicColorPreview'),
  TypeScaleSamples: clientComponent('TypeScaleSamples'),
  CheckboxPreview: clientComponent('CheckboxPreview'),
  RadioButtonPreview: clientComponent('RadioButtonPreview'),
  SwitchPreview: clientComponent('SwitchPreview'),
  SliderPreview: clientComponent('SliderPreview'),
  CardPreview: clientComponent('CardPreview'),
  ChipPreview: clientComponent('ChipPreview'),
  IconButtonPreview: clientComponent('IconButtonPreview'),
  FabPreview: clientComponent('FabPreview'),
  Button: clientComponent('Button'),
  ElevatedButton: clientComponent('ElevatedButton'),
  FilledTonalButton: clientComponent('FilledTonalButton'),
  OutlinedButton: clientComponent('OutlinedButton'),
  TextButton: clientComponent('TextButton'),
  TextField: clientComponent('TextField'),
  OutlinedTextField: clientComponent('OutlinedTextField'),
  SecureTextField: clientComponent('SecureTextField'),
  OutlinedSecureTextField: clientComponent('OutlinedSecureTextField'),
  DialogTrigger: clientComponent('DialogTrigger'),
  DialogOverlay: clientComponent('DialogOverlay'),
  Dialog: clientComponent('Dialog'),
  DialogIcon: clientComponent('DialogIcon'),
  DialogTitle: clientComponent('DialogTitle'),
  DialogDescription: clientComponent('DialogDescription'),
  DialogActions: clientComponent('DialogActions'),
  DialogAction: clientComponent('DialogAction'),
  DialogCloseAction: clientComponent('DialogCloseAction'),
  ComponentHero: clientComponent('ComponentHero'),
  SourceLinks: clientComponent('SourceLinks'),
  GuidanceCallout: clientComponent('GuidanceCallout'),
  AnatomyBlock: clientComponent('AnatomyBlock'),
  FidelitySummary: clientComponent('FidelitySummary'),
  RelatedComponents: clientComponent('RelatedComponents'),
  GeneratedApiReferenceSlot: clientComponent('GeneratedApiReferenceSlot'),
  PageSectionNote: clientComponent('PageSectionNote'),
  SearchBarPreview: clientComponent('SearchBarPreview'),
  ProgressIndicatorPreview: clientComponent('ProgressIndicatorPreview'),
  LoadingIndicatorPreview: clientComponent('LoadingIndicatorPreview'),
  SnackbarPreview: clientComponent('SnackbarPreview'),
  TooltipPreview: clientComponent('TooltipPreview'),
  TabsPreview: clientComponent('TabsPreview'),
  SegmentedButtonPreview: clientComponent('SegmentedButtonPreview'),
  SplitButtonPreview: clientComponent('SplitButtonPreview'),
  ButtonGroupPreview: clientComponent('ButtonGroupPreview'),
  ListItemPreview: clientComponent('ListItemPreview'),
  MenuPreview: clientComponent('MenuPreview'),
  BadgePreview: clientComponent('BadgePreview'),
  DividerPreview: clientComponent('DividerPreview'),
  DatePickerPreview: clientComponent('DatePickerPreview'),
  TimePickerPreview: clientComponent('TimePickerPreview'),
  BottomSheetPreview: clientComponent('BottomSheetPreview'),
  CarouselPreview: clientComponent('CarouselPreview'),
  ModalBottomSheetPreview: clientComponent('ModalBottomSheetPreview'),
  PullToRefreshPreview: clientComponent('PullToRefreshPreview'),
  ScrollFieldPreview: clientComponent('ScrollFieldPreview'),
  SwipeToDismissPreview: clientComponent('SwipeToDismissPreview'),
  SurfacePreview: clientComponent('SurfacePreview'),
  ScrimPreview: clientComponent('ScrimPreview'),
  VerticalDragHandlePreview: clientComponent('VerticalDragHandlePreview'),
  NonInteractiveScrollbarPreview: clientComponent('NonInteractiveScrollbarPreview'),
  TopAppBarPreview: clientComponent('TopAppBarPreview'),
  BottomAppBarPreview: clientComponent('BottomAppBarPreview'),
  FloatingToolbarPreview: clientComponent('FloatingToolbarPreview'),
  ToggleButtonPreview: clientComponent('ToggleButtonPreview'),
  FabMenuPreview: clientComponent('FabMenuPreview'),
  AppBarOverflowPreview: clientComponent('AppBarOverflowPreview'),
  ParityCatalog: clientComponent('ParityCatalog'),
  MaterialFidelity: clientComponent('MaterialFidelity'),
} satisfies MDXComponents;
