import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import { androidX } from './manifest.mjs';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, '../..');
const generatedDir = resolve(
  repoRoot,
  'packages/tokens/src/generated/androidx',
);

async function generatedModules() {
  return (await readdir(generatedDir))
    .filter((name) => name.endsWith('.ts') && name !== 'index.ts')
    .sort();
}

test('generated barrel exports every committed module exactly once', async () => {
  const modules = await generatedModules();
  assert.ok(modules.length > 0, 'generated token snapshot must not be empty');

  const index = await readFile(resolve(generatedDir, 'index.ts'), 'utf8');
  const exports = [...index.matchAll(/export \* from '\.\/(.+)\.js';/g)]
    .map((match) => `${match[1]}.ts`)
    .sort();
  assert.deepEqual(exports, modules);
  assert.equal(new Set(exports).size, exports.length);
});

test('every generated module has pinned AndroidX provenance and one token export', async () => {
  const modules = await generatedModules();
  const paths = new Set();
  const blobs = new Set();

  for (const module of modules) {
    const content = await readFile(resolve(generatedDir, module), 'utf8');
    assert.match(content, /Generated by scripts\/compose-sync\. DO NOT EDIT\./);
    assert.ok(content.includes(`revision: '${androidX.revision}'`));

    const path = content.match(/\n  path: '([^']+)',/)?.[1];
    const blob = content.match(/\n  blobSha: '([0-9a-f]{40})',/)?.[1];
    assert.ok(path, `${module} must record upstream path`);
    assert.ok(
      path.startsWith(`${androidX.tokenRoot}/`) && path.endsWith('Tokens.kt'),
      `${module} must point at a direct Material3 token source`,
    );
    assert.ok(blob, `${module} must record upstream blob SHA`);
    assert.match(content, /export const \w+TokensGenerated = \{/);

    assert.equal(paths.has(path), false, `duplicate upstream path: ${path}`);
    assert.equal(blobs.has(blob), false, `duplicate upstream blob: ${blob}`);
    paths.add(path);
    blobs.add(blob);
  }
});

test('committed snapshot includes foundations and unported component families', async () => {
  const modules = new Set(await generatedModules());
  for (const required of [
    'elevation.ts',
    'shape.ts',
    'type-scale.ts',
    'state.ts',
    'motion.ts',
    'filled-button.ts',
    'switch.ts',
    'app-bar.ts',
    'badge.ts',
  ]) {
    assert.ok(modules.has(required), `${required} must be discovered upstream`);
  }
});
