import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import { androidX, tokenSources } from './manifest.mjs';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, '../..');
const generatedDir = resolve(
  repoRoot,
  'packages/tokens/src/generated/androidx',
);

function relativeGeneratedPath(source) {
  return source.output.split('/').at(-1);
}

test('committed generated directory exactly matches the manifest plus barrel', async () => {
  const actual = (await readdir(generatedDir))
    .filter((name) => name.endsWith('.ts'))
    .sort();
  const expected = [
    'index.ts',
    ...tokenSources.map(relativeGeneratedPath),
  ].sort();
  assert.deepEqual(actual, expected);
});

test('generated barrel exports every manifest module exactly once', async () => {
  const index = await readFile(resolve(generatedDir, 'index.ts'), 'utf8');
  const exports = [...index.matchAll(/export \* from '\.\/(.+)\.js';/g)]
    .map((match) => `${match[1]}.ts`)
    .sort();
  const expected = tokenSources.map(relativeGeneratedPath).sort();
  assert.deepEqual(exports, expected);
});

test('every generated module records exact manifest provenance and export', async () => {
  await Promise.all(
    tokenSources.map(async (source) => {
      const content = await readFile(resolve(repoRoot, source.output), 'utf8');
      assert.match(content, /Generated by scripts\/compose-sync\. DO NOT EDIT\./);
      assert.ok(
        content.includes(`revision: '${androidX.revision}'`),
        `${source.file} revision provenance`,
      );
      assert.ok(
        content.includes(`path: '${source.path}'`),
        `${source.file} path provenance`,
      );
      assert.ok(
        content.includes(`blobSha: '${source.blobSha}'`),
        `${source.file} blob provenance`,
      );
      assert.ok(
        content.includes(`export const ${source.exportName} = {`),
        `${source.file} generated export`,
      );
    }),
  );
});
