import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, rename, rm, writeFile } from 'node:fs/promises';
import { basename, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  androidX,
  tokenSourcesFromDirectory,
} from './manifest.mjs';
import {
  parseAndroidXTokenFile,
  renderGeneratedTokenModule,
} from './parser.mjs';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, '../..');
const generatedDir = resolve(
  repoRoot,
  'packages/tokens/src/generated/androidx',
);
const check = process.argv.includes('--check');

function gitBlobSha(content) {
  const bytes = Buffer.from(content);
  return createHash('sha1')
    .update(Buffer.from(`blob ${bytes.length}\0`))
    .update(bytes)
    .digest('hex');
}

function rawUrl(source) {
  return `https://raw.githubusercontent.com/${androidX.repository}/${androidX.revision}/${source.path}`;
}

function directoryUrl() {
  return `https://api.github.com/repos/${androidX.repository}/contents/${androidX.tokenRoot}?ref=${androidX.revision}`;
}

async function fetchWithRetry(url, description, options = {}) {
  let lastError;
  for (let attempt = 1; attempt <= 3; attempt += 1) {
    try {
      const response = await fetch(url, {
        ...options,
        headers: {
          'user-agent': 'm3-ui-compose-sync',
          ...(options.headers ?? {}),
        },
      });
      if (!response.ok) {
        throw new Error(`${response.status} ${response.statusText}`);
      }
      return response;
    } catch (error) {
      lastError = error;
      if (attempt < 3) {
        await new Promise((done) => setTimeout(done, attempt * 250));
      }
    }
  }
  throw new Error(`Failed to fetch ${description}: ${lastError}`);
}

async function discoverTokenSources() {
  const response = await fetchWithRetry(
    directoryUrl(),
    `AndroidX token directory ${androidX.tokenRoot}`,
    { headers: { accept: 'application/vnd.github+json' } },
  );
  return tokenSourcesFromDirectory(await response.json());
}

async function fetchText(source) {
  const response = await fetchWithRetry(rawUrl(source), source.path);
  return response.text();
}

async function mapConcurrent(items, limit, mapper) {
  const results = new Array(items.length);
  let cursor = 0;

  async function worker() {
    while (cursor < items.length) {
      const index = cursor;
      cursor += 1;
      results[index] = await mapper(items[index], index);
    }
  }

  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, () => worker()),
  );
  return results;
}

function renderIndex(tokenSources) {
  const lines = tokenSources.map((source) => {
    const file = basename(source.output).replace(/\.ts$/, '.js');
    return `export * from './${file}';`;
  });
  return `// Generated by scripts/compose-sync. DO NOT EDIT.\n${lines.join('\n')}\n`;
}

function collectRefs(value, refs) {
  if (!value || typeof value !== 'object') return;
  if (value.kind === 'ref') refs.push(value);
  if (Array.isArray(value)) {
    for (const item of value) collectRefs(item, refs);
    return;
  }
  for (const item of Object.values(value)) collectRefs(item, refs);
}

function tokenSetName(source) {
  const objectName = source.file.replace(/\.kt$/, '');
  const stem = objectName.slice(0, -'Tokens'.length);
  return stem.length === 0 ? stem : stem[0].toLowerCase() + stem.slice(1);
}

function validateDependencyClosure(parsedBatch, tokenSources) {
  const availableSets = new Set(tokenSources.map(tokenSetName));
  for (const { source, parsed } of parsedBatch) {
    const refs = [];
    collectRefs(parsed.tokens, refs);
    const missing = [...new Set(refs.map((ref) => ref.set))].filter(
      (set) => !availableSets.has(set),
    );
    if (missing.length > 0) {
      throw new Error(
        `Untracked token dependency from ${source.file}: ${missing.join(', ')}`,
      );
    }
  }
}

async function checkSnapshot(renderedBatch) {
  const mismatches = [];
  const expectedNames = renderedBatch.map((output) => basename(output.path)).sort();
  let actualNames = [];
  try {
    actualNames = (await readdir(generatedDir))
      .filter((name) => name.endsWith('.ts'))
      .sort();
  } catch {
    mismatches.push('generated directory is missing');
  }

  if (JSON.stringify(actualNames) !== JSON.stringify(expectedNames)) {
    const expected = new Set(expectedNames);
    const actual = new Set(actualNames);
    for (const name of expectedNames) {
      if (!actual.has(name)) mismatches.push(`missing ${name}`);
    }
    for (const name of actualNames) {
      if (!expected.has(name)) mismatches.push(`extra ${name}`);
    }
  }

  for (const output of renderedBatch) {
    let actual = '';
    try {
      actual = await readFile(resolve(generatedDir, basename(output.path)), 'utf8');
    } catch {
      continue;
    }
    if (actual !== output.expected) {
      mismatches.push(`stale ${basename(output.path)}`);
    }
  }
  return mismatches;
}

async function writeSnapshot(renderedBatch) {
  const parent = dirname(generatedDir);
  const tempDir = resolve(parent, `.androidx-sync-${process.pid}`);
  const backupDir = resolve(parent, `.androidx-backup-${process.pid}`);
  await rm(tempDir, { recursive: true, force: true });
  await rm(backupDir, { recursive: true, force: true });
  await mkdir(tempDir, { recursive: true });

  for (const output of renderedBatch) {
    await writeFile(
      resolve(tempDir, basename(output.path)),
      output.expected,
      'utf8',
    );
  }

  let movedExisting = false;
  try {
    try {
      await rename(generatedDir, backupDir);
      movedExisting = true;
    } catch (error) {
      if (error?.code !== 'ENOENT') throw error;
    }
    await rename(tempDir, generatedDir);
    if (movedExisting) await rm(backupDir, { recursive: true, force: true });
  } catch (error) {
    await rm(tempDir, { recursive: true, force: true });
    try {
      await rm(generatedDir, { recursive: true, force: true });
      if (movedExisting) await rename(backupDir, generatedDir);
    } catch {
      // Preserve the original write error; recovery is best-effort.
    }
    throw error;
  }
}

// Stage 0: discover every *Tokens.kt file from the exact pinned AndroidX commit.
// The directory is not curated by this repository; future component token files are
// included automatically when the pinned revision is intentionally advanced.
const tokenSources = await discoverTokenSources();

// Stage 1: fetch every discovered source and verify raw bytes against the blob SHA
// returned by GitHub for that exact commit.
const fetched = await mapConcurrent(tokenSources, 8, async (source) => {
  const content = await fetchText(source);
  const actualBlobSha = gitBlobSha(content);
  if (actualBlobSha !== source.blobSha) {
    throw new Error(
      `Pinned source mismatch for ${source.path}: expected ${source.blobSha}, got ${actualBlobSha}`,
    );
  }
  return { source, content };
});

// Stage 2: parse/render the complete directory in memory. Nothing is written until
// every source has parsed and the token-reference dependency graph is closed.
const parsedBatch = fetched.map(({ source, content }) => ({
  source,
  parsed: parseAndroidXTokenFile(content, source.path),
}));
validateDependencyClosure(parsedBatch, tokenSources);

const renderedBatch = parsedBatch.map(({ source, parsed }) => ({
  path: source.output,
  expected: renderGeneratedTokenModule({
    revision: androidX.revision,
    sourcePath: source.path,
    blobSha: source.blobSha,
    exportName: source.exportName,
    parsed,
  }),
}));
renderedBatch.push({
  path: 'packages/tokens/src/generated/androidx/index.ts',
  expected: renderIndex(tokenSources),
});

// Stage 3: compare the entire committed directory in CI, including extra/missing
// files, or replace it as one snapshot after the full batch has validated.
if (check) {
  const mismatches = await checkSnapshot(renderedBatch);
  if (mismatches.length > 0) {
    console.error(
      'Compose token sync is stale. Regenerate with `pnpm compose:sync`:',
    );
    for (const mismatch of mismatches) console.error(`- ${mismatch}`);
    process.exitCode = 1;
  } else {
    console.log(
      `Verified ${tokenSources.length} token modules discovered from AndroidX ${androidX.revision}; every source blob parsed and verified in one batch.`,
    );
  }
} else {
  await writeSnapshot(renderedBatch);
  console.log(
    `Generated ${tokenSources.length} token modules discovered from AndroidX ${androidX.revision}; every source blob parsed and verified in one batch.`,
  );
}
