import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { androidX, tokenSources } from './manifest.mjs';
import {
  parseAndroidXTokenFile,
  renderGeneratedTokenModule,
} from './parser.mjs';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, '../..');
const check = process.argv.includes('--check');

function gitBlobSha(content) {
  const bytes = Buffer.from(content);
  return createHash('sha1')
    .update(Buffer.from(`blob ${bytes.length}\0`))
    .update(bytes)
    .digest('hex');
}

function rawUrl(source) {
  return `https://raw.githubusercontent.com/${androidX.repository}/${androidX.revision}/${source.path}`;
}

async function fetchText(source) {
  let lastError;
  for (let attempt = 1; attempt <= 3; attempt += 1) {
    try {
      const response = await fetch(rawUrl(source), {
        headers: { 'user-agent': 'm3-ui-compose-sync' },
      });
      if (!response.ok) {
        throw new Error(`${response.status} ${response.statusText}`);
      }
      return await response.text();
    } catch (error) {
      lastError = error;
      if (attempt < 3) {
        await new Promise((done) => setTimeout(done, attempt * 250));
      }
    }
  }
  throw new Error(`Failed to fetch ${source.path}: ${lastError}`);
}

async function mapConcurrent(items, limit, mapper) {
  const results = new Array(items.length);
  let cursor = 0;

  async function worker() {
    while (cursor < items.length) {
      const index = cursor;
      cursor += 1;
      results[index] = await mapper(items[index], index);
    }
  }

  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, () => worker()),
  );
  return results;
}

function renderIndex() {
  const lines = tokenSources.map((source) => {
    const file = source.output.split('/').at(-1).replace(/\.ts$/, '.js');
    return `export * from './${file}';`;
  });
  return `// Generated by scripts/compose-sync. DO NOT EDIT.\n${lines.join('\n')}\n`;
}

function collectRefs(value, refs) {
  if (!value || typeof value !== 'object') return;
  if (value.kind === 'ref') refs.push(value);
  if (Array.isArray(value)) {
    for (const item of value) collectRefs(item, refs);
    return;
  }
  for (const item of Object.values(value)) collectRefs(item, refs);
}

function tokenSetName(source) {
  const objectName = source.file.replace(/\.kt$/, '');
  const stem = objectName.slice(0, -'Tokens'.length);
  return stem.length === 0 ? stem : stem[0].toLowerCase() + stem.slice(1);
}

function validateDependencyClosure(parsedBatch) {
  const availableSets = new Set(tokenSources.map(tokenSetName));
  for (const { source, parsed } of parsedBatch) {
    const refs = [];
    collectRefs(parsed.tokens, refs);
    const missing = [...new Set(refs.map((ref) => ref.set))].filter(
      (set) => !availableSets.has(set),
    );
    if (missing.length > 0) {
      throw new Error(
        `Untracked token dependency from ${source.file}: ${missing.join(', ')}`,
      );
    }
  }
}

async function verifyOrWrite(path, expected, mismatches) {
  const absolute = resolve(repoRoot, path);
  if (check) {
    let actual = '';
    try {
      actual = await readFile(absolute, 'utf8');
    } catch {
      mismatches.push(path);
      return;
    }
    if (actual !== expected) mismatches.push(path);
    return;
  }

  await mkdir(dirname(absolute), { recursive: true });
  await writeFile(absolute, expected, 'utf8');
}

// Stage 1: fetch every tracked source and verify exact pinned Git blob bytes.
const fetched = await mapConcurrent(tokenSources, 6, async (source) => {
  const content = await fetchText(source);
  const actualBlobSha = gitBlobSha(content);
  if (actualBlobSha !== source.blobSha) {
    throw new Error(
      `Pinned source mismatch for ${source.path}: expected ${source.blobSha}, got ${actualBlobSha}`,
    );
  }
  return { source, content };
});

// Stage 2: parse and render the complete batch in memory. Nothing is written until
// every source has parsed successfully, so generation cannot leave a partial snapshot.
const parsedBatch = fetched.map(({ source, content }) => ({
  source,
  parsed: parseAndroidXTokenFile(content, source.path),
}));
validateDependencyClosure(parsedBatch);

const renderedBatch = parsedBatch.map(({ source, parsed }) => ({
  path: source.output,
  expected: renderGeneratedTokenModule({
    revision: androidX.revision,
    sourcePath: source.path,
    blobSha: source.blobSha,
    exportName: source.exportName,
    parsed,
  }),
}));
renderedBatch.push({
  path: 'packages/tokens/src/generated/androidx/index.ts',
  expected: renderIndex(),
});

// Stage 3: only after the full batch is valid, atomically-at-the-batch-level
// write files or compare the committed snapshot byte-for-byte in CI.
const mismatches = [];
for (const output of renderedBatch) {
  await verifyOrWrite(output.path, output.expected, mismatches);
}

if (check && mismatches.length > 0) {
  console.error(
    'Compose token sync is stale. Regenerate these files with `pnpm compose:sync`:',
  );
  for (const path of mismatches) {
    console.error(`- ${relative(repoRoot, resolve(repoRoot, path))}`);
  }
  process.exitCode = 1;
} else {
  console.log(
    `${check ? 'Verified' : 'Generated'} ${tokenSources.length} token modules from AndroidX ${androidX.revision}; ${tokenSources.length} source blobs parsed and verified in one batch.`,
  );
}
