import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { androidX, tokenSources } from './manifest.mjs';
import {
  parseAndroidXTokenFile,
  renderGeneratedTokenModule,
} from './parser.mjs';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, '../..');
const check = process.argv.includes('--check');
const generatedSources = tokenSources.filter((source) => source.output);

function gitBlobSha(content) {
  const bytes = Buffer.from(content);
  return createHash('sha1')
    .update(Buffer.from(`blob ${bytes.length}\0`))
    .update(bytes)
    .digest('hex');
}

function rawUrl(source) {
  return `https://raw.githubusercontent.com/${androidX.repository}/${androidX.revision}/${source.path}`;
}

async function fetchText(source) {
  let lastError;
  for (let attempt = 1; attempt <= 3; attempt += 1) {
    try {
      const response = await fetch(rawUrl(source), {
        headers: { 'user-agent': 'm3-ui-compose-sync' },
      });
      if (!response.ok) {
        throw new Error(`${response.status} ${response.statusText}`);
      }
      return await response.text();
    } catch (error) {
      lastError = error;
      if (attempt < 3) {
        await new Promise((done) => setTimeout(done, attempt * 250));
      }
    }
  }
  throw new Error(`Failed to fetch ${source.path}: ${lastError}`);
}

async function mapConcurrent(items, limit, mapper) {
  const results = new Array(items.length);
  let cursor = 0;

  async function worker() {
    while (cursor < items.length) {
      const index = cursor;
      cursor += 1;
      results[index] = await mapper(items[index], index);
    }
  }

  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, () => worker()),
  );
  return results;
}

function renderIndex() {
  const lines = generatedSources.map((source) => {
    const file = source.output.split('/').at(-1).replace(/\.ts$/, '.js');
    return `export * from './${file}';`;
  });
  return `// Generated by scripts/compose-sync. DO NOT EDIT.\n${lines.join('\n')}\n`;
}

async function verifyOrWrite(path, expected, mismatches) {
  const absolute = resolve(repoRoot, path);
  if (check) {
    let actual = '';
    try {
      actual = await readFile(absolute, 'utf8');
    } catch {
      mismatches.push(path);
      return;
    }
    if (actual !== expected) mismatches.push(path);
    return;
  }

  await mkdir(dirname(absolute), { recursive: true });
  await writeFile(absolute, expected, 'utf8');
}

const fetched = await mapConcurrent(tokenSources, 6, async (source) => {
  const content = await fetchText(source);
  const actualBlobSha = gitBlobSha(content);
  if (actualBlobSha !== source.blobSha) {
    throw new Error(
      `Pinned source mismatch for ${source.path}: expected ${source.blobSha}, got ${actualBlobSha}`,
    );
  }
  return { source, content };
});

const mismatches = [];
for (const { source, content } of fetched) {
  if (!source.output) continue;
  const parsed = parseAndroidXTokenFile(content, source.path);
  const generated = renderGeneratedTokenModule({
    revision: androidX.revision,
    sourcePath: source.path,
    blobSha: source.blobSha,
    exportName: source.exportName,
    parsed,
  });
  await verifyOrWrite(source.output, generated, mismatches);
}

await verifyOrWrite(
  'packages/tokens/src/generated/androidx/index.ts',
  renderIndex(),
  mismatches,
);

if (check && mismatches.length > 0) {
  console.error(
    'Compose token sync is stale. Regenerate these files with `pnpm compose:sync`:',
  );
  for (const path of mismatches) {
    console.error(`- ${relative(repoRoot, resolve(repoRoot, path))}`);
  }
  process.exitCode = 1;
} else {
  console.log(
    `${check ? 'Verified' : 'Generated'} ${generatedSources.length} token modules from AndroidX ${androidX.revision}; ${tokenSources.length} source blobs verified.`,
  );
}
