import * as token from '@m3-ui/tokens';
import type { ColorScheme, ThemeMode } from './types';

// Baseline Material values are canonical DTCG in @m3-ui/tokens. These objects
// are the typed JavaScript view required by useTheme().scheme and public helpers.
export const lightColorScheme = {
  background: token.ThemeBaselineLightBackground,
  onBackground: token.ThemeBaselineLightOnBackground,
  surface: token.ThemeBaselineLightSurface,
  surfaceDim: token.ThemeBaselineLightSurfaceDim,
  surfaceBright: token.ThemeBaselineLightSurfaceBright,
  surfaceContainerLowest: token.ThemeBaselineLightSurfaceContainerLowest,
  surfaceContainerLow: token.ThemeBaselineLightSurfaceContainerLow,
  surfaceContainer: token.ThemeBaselineLightSurfaceContainer,
  surfaceContainerHigh: token.ThemeBaselineLightSurfaceContainerHigh,
  surfaceContainerHighest: token.ThemeBaselineLightSurfaceContainerHighest,
  onSurface: token.ThemeBaselineLightOnSurface,
  surfaceVariant: token.ThemeBaselineLightSurfaceVariant,
  onSurfaceVariant: token.ThemeBaselineLightOnSurfaceVariant,
  inverseSurface: token.ThemeBaselineLightInverseSurface,
  inverseOnSurface: token.ThemeBaselineLightInverseOnSurface,
  outline: token.ThemeBaselineLightOutline,
  outlineVariant: token.ThemeBaselineLightOutlineVariant,
  shadow: token.ThemeBaselineLightShadow,
  scrim: token.ThemeBaselineLightScrim,
  surfaceTint: token.ThemeBaselineLightSurfaceTint,
  primary: token.ThemeBaselineLightPrimary,
  onPrimary: token.ThemeBaselineLightOnPrimary,
  primaryContainer: token.ThemeBaselineLightPrimaryContainer,
  onPrimaryContainer: token.ThemeBaselineLightOnPrimaryContainer,
  inversePrimary: token.ThemeBaselineLightInversePrimary,
  primaryFixed: token.ThemeBaselineLightPrimaryFixed,
  primaryFixedDim: token.ThemeBaselineLightPrimaryFixedDim,
  onPrimaryFixed: token.ThemeBaselineLightOnPrimaryFixed,
  onPrimaryFixedVariant: token.ThemeBaselineLightOnPrimaryFixedVariant,
  secondary: token.ThemeBaselineLightSecondary,
  onSecondary: token.ThemeBaselineLightOnSecondary,
  secondaryContainer: token.ThemeBaselineLightSecondaryContainer,
  onSecondaryContainer: token.ThemeBaselineLightOnSecondaryContainer,
  secondaryFixed: token.ThemeBaselineLightSecondaryFixed,
  secondaryFixedDim: token.ThemeBaselineLightSecondaryFixedDim,
  onSecondaryFixed: token.ThemeBaselineLightOnSecondaryFixed,
  onSecondaryFixedVariant: token.ThemeBaselineLightOnSecondaryFixedVariant,
  tertiary: token.ThemeBaselineLightTertiary,
  onTertiary: token.ThemeBaselineLightOnTertiary,
  tertiaryContainer: token.ThemeBaselineLightTertiaryContainer,
  onTertiaryContainer: token.ThemeBaselineLightOnTertiaryContainer,
  tertiaryFixed: token.ThemeBaselineLightTertiaryFixed,
  tertiaryFixedDim: token.ThemeBaselineLightTertiaryFixedDim,
  onTertiaryFixed: token.ThemeBaselineLightOnTertiaryFixed,
  onTertiaryFixedVariant: token.ThemeBaselineLightOnTertiaryFixedVariant,
  error: token.ThemeBaselineLightError,
  onError: token.ThemeBaselineLightOnError,
  errorContainer: token.ThemeBaselineLightErrorContainer,
  onErrorContainer: token.ThemeBaselineLightOnErrorContainer,
} as const satisfies ColorScheme;

export const darkColorScheme = {
  background: token.ThemeBaselineDarkBackground,
  onBackground: token.ThemeBaselineDarkOnBackground,
  surface: token.ThemeBaselineDarkSurface,
  surfaceDim: token.ThemeBaselineDarkSurfaceDim,
  surfaceBright: token.ThemeBaselineDarkSurfaceBright,
  surfaceContainerLowest: token.ThemeBaselineDarkSurfaceContainerLowest,
  surfaceContainerLow: token.ThemeBaselineDarkSurfaceContainerLow,
  surfaceContainer: token.ThemeBaselineDarkSurfaceContainer,
  surfaceContainerHigh: token.ThemeBaselineDarkSurfaceContainerHigh,
  surfaceContainerHighest: token.ThemeBaselineDarkSurfaceContainerHighest,
  onSurface: token.ThemeBaselineDarkOnSurface,
  surfaceVariant: token.ThemeBaselineDarkSurfaceVariant,
  onSurfaceVariant: token.ThemeBaselineDarkOnSurfaceVariant,
  inverseSurface: token.ThemeBaselineDarkInverseSurface,
  inverseOnSurface: token.ThemeBaselineDarkInverseOnSurface,
  outline: token.ThemeBaselineDarkOutline,
  outlineVariant: token.ThemeBaselineDarkOutlineVariant,
  shadow: token.ThemeBaselineDarkShadow,
  scrim: token.ThemeBaselineDarkScrim,
  surfaceTint: token.ThemeBaselineDarkSurfaceTint,
  primary: token.ThemeBaselineDarkPrimary,
  onPrimary: token.ThemeBaselineDarkOnPrimary,
  primaryContainer: token.ThemeBaselineDarkPrimaryContainer,
  onPrimaryContainer: token.ThemeBaselineDarkOnPrimaryContainer,
  inversePrimary: token.ThemeBaselineDarkInversePrimary,
  primaryFixed: token.ThemeBaselineDarkPrimaryFixed,
  primaryFixedDim: token.ThemeBaselineDarkPrimaryFixedDim,
  onPrimaryFixed: token.ThemeBaselineDarkOnPrimaryFixed,
  onPrimaryFixedVariant: token.ThemeBaselineDarkOnPrimaryFixedVariant,
  secondary: token.ThemeBaselineDarkSecondary,
  onSecondary: token.ThemeBaselineDarkOnSecondary,
  secondaryContainer: token.ThemeBaselineDarkSecondaryContainer,
  onSecondaryContainer: token.ThemeBaselineDarkOnSecondaryContainer,
  secondaryFixed: token.ThemeBaselineDarkSecondaryFixed,
  secondaryFixedDim: token.ThemeBaselineDarkSecondaryFixedDim,
  onSecondaryFixed: token.ThemeBaselineDarkOnSecondaryFixed,
  onSecondaryFixedVariant: token.ThemeBaselineDarkOnSecondaryFixedVariant,
  tertiary: token.ThemeBaselineDarkTertiary,
  onTertiary: token.ThemeBaselineDarkOnTertiary,
  tertiaryContainer: token.ThemeBaselineDarkTertiaryContainer,
  onTertiaryContainer: token.ThemeBaselineDarkOnTertiaryContainer,
  tertiaryFixed: token.ThemeBaselineDarkTertiaryFixed,
  tertiaryFixedDim: token.ThemeBaselineDarkTertiaryFixedDim,
  onTertiaryFixed: token.ThemeBaselineDarkOnTertiaryFixed,
  onTertiaryFixedVariant: token.ThemeBaselineDarkOnTertiaryFixedVariant,
  error: token.ThemeBaselineDarkError,
  onError: token.ThemeBaselineDarkOnError,
  errorContainer: token.ThemeBaselineDarkErrorContainer,
  onErrorContainer: token.ThemeBaselineDarkOnErrorContainer,
} as const satisfies ColorScheme;

export function getBaselineColorScheme(mode: ThemeMode): ColorScheme {
  return mode === 'dark' ? darkColorScheme : lightColorScheme;
}
