import type { CSSProperties } from 'react';
import type { ChipVariant } from './Chip.tokens';

export type ChipStyle = CSSProperties & Record<`--${string}`, string | number>;
export type ChipShapeValue = string | number;
export interface ChipShapes {
  readonly shape?: ChipShapeValue;
  readonly selectedShape?: ChipShapeValue;
  readonly pressedShape?: ChipShapeValue;
}
export interface ChipRuntimeState {
  readonly isDisabled: boolean;
  readonly isSelected?: boolean;
  readonly isPressed?: boolean;
}
export interface ChipStyleOptions {
  readonly shape?: ChipShapeValue;
  readonly shapes?: ChipShapes;
  readonly hasLeadingIcon?: boolean;
  readonly hasTrailingIcon?: boolean;
  readonly hasAvatar?: boolean;
}

function normalizeShape(value: ChipShapeValue): string | number {
  return typeof value === 'number' ? `${value}px` : value;
}

/**
 * Serializes only real instance-level shape overrides. Immutable Chip
 * dimensions, typography, spacing, default shapes and motion are generated by
 * Style Dictionary in `@m3-ui/tokens/chip.css`.
 */
export function getChipStyle(
  _variant: ChipVariant,
  state: ChipRuntimeState,
  options: ChipStyleOptions = {},
): ChipStyle {
  if (options.shapes) {
    const value = state.isPressed
      ? options.shapes.pressedShape
      : state.isSelected
        ? options.shapes.selectedShape
        : options.shapes.shape;
    return value === undefined
      ? {}
      : { '--_chip-container-radius': normalizeShape(value) };
  }

  return options.shape === undefined
    ? {}
    : { '--_chip-container-radius': normalizeShape(options.shape) };
}
